### ISSUE TITLE
Umods how do install these?

### ISSUE THREAD

**Issue by shandshellin** [PhasecoreX/docker-ut99-server#10]
Some mods only come in a mod format, howdo you install these manually?

**Comment by PhasecoreX** [comment]
If there isn't a non-umod version, you can use a umod extractor to get all the contents of the umod file, then move them to the appropriate folders.

Something like [this](https://ut99.org/viewtopic.php?t=14294) or [this](https://unrealadmin.org/forums/showthread.php?t=6490).

Just make sure if it's one of those umods that adds serverpackage lines to the unrealtournament.ini, remember to do that manually.

**Comment by shandshellin** [comment]
that worked, thanks! 2 other questions. I can connect via local ip and port but any reason it won't show up under LAN games? Windows firewall on the client side looks good. Any idea on how to get the weapon icon smaller or scaled properly in the client, it takes up the screen alot. That's not really yours to fix or anything just thought as another passion player you may have come across that, i have an UW monitor.

**Comment by shandshellin** [comment]
So all mods and m,aps go into the addons folder structure? If i want to edit the unrealtournament.ini which one do i use the addons location or the server folder?

**Comment by PhasecoreX** [comment]
For LAN, you need to have UDP port 8777 open/forwarded (`-p 8777:8777/udp`), assuming you're using the default port 7777 for the game port. LAN port is game port + 1000. See https://github.com/PhasecoreX/docker-ut99-server?tab=readme-ov-file#ports for more details.

For my ultrawide monitor I use https://github.com/alexstrout/foxWSFix-UT99

The `/data/server` folder, pretty much don't touch it or add anything to it. All the .ini files in `/data/server/System` should have been automatically moved over to the `/data/addons/System` folder. All your addon maps and stuff should also go into `/data/addons`, as well as modifying any .ini files in `/data/addons/System`.

The idea is that a base fresh untouched ut99 server is in the `/data/server` folder, and then all the customization/addons go in the `/data/addons` for easy management.

**Comment by shandshellin** [comment]
For the LAN i had to set port 8777 in docker to be on host and not on the ingress network, now i can see it.

I think i installed the uw fix correctly but the directions are vague for file placement and i get a launch error stating it cannot find foxWSFix99.

**Comment by PhasecoreX** [comment]
All you'd have to do is extract the Help and System directories and then edit `System\UnrealTournament.ini`, changing
```
Console=UTMenu.UTConsole
```
to
```
;Console=UTMenu.UTConsole
Console=foxWSFix99.foxUTConsole
```
That should be it. You should have `foxWSFix99.u` file in the System directory and `foxWSFix Readme.txt` in the Help directory if you extracted it right. Also this is for the game, not the server. Server doesn't need this, and probably shouldn't have it at all.

I'll close this now, since it seems you are good with the server now. If not, let me know here. Enjoy!

**Comment by shandshellin** [comment]
The archive has a foxUTConsole.uc but nothing else, a compile file or something. Not matching what the instructions say. 

So regarding the Chaos and u4e mods if you use them, there was a way back in the day that you could customize the mutator settings. You would configure the weapon types etc in chaos ut on your client then you would copy the chaos file from your client to the server and it would then have those settings. Do you know about that? Maybe just copy all the chaos and u4e files from system to addons /system? Not sure where the mos setting are stored.

**Comment by PhasecoreX** [comment]
You have to get the release from here https://github.com/alexstrout/foxWSFix-UT99/releases/tag/v1.1.1, as that .uc file is the source code, not compiled.

And yeah I don't know about chaos or u4e specifically, but if you configure them in the client, you would either see their own .ini files being updated, or you'd see them update the UnrealTournament.ini with a new section. For their own .ini files, just copy them to the `/data/addons/System` directory. For mods that update UnrealTournament.ini, you'll have to manually copy and paste the sections in them over to the servers `/data/addons/System/UnrealTournament.ini`

**Comment by shandshellin** [comment]
That worked perfectly, thank you! Do you know how to have this server so the bots will keep playing and the matches will keep cycling even without an actual player?

**Comment by PhasecoreX** [comment]
I am not sure how to do that. Usually it waits for at least one human to start. There might be a setting to disable that, or possibly a mutator to do that, but I wouldn't know of any.
