### ISSUE TITLE
RPI4 No matching manifest

### ISSUE THREAD

**Issue by KyrosWeb** [PhasecoreX/docker-ut99-server#9]
Hi , this is the error I have when i try to download the docker container.

`docker: no matching manifest for linux/arm64/v8 in the manifest list entries.`

Could you fix it?

**Comment by PhasecoreX** [comment]
Wow, set it all up for arm64 and forgot to [actually tell it to build](https://github.com/PhasecoreX/docker-ut99-server/commit/e82e188cdf399fba5f2887e07611fc86870546b2). Should be fixed now, can you please try again?

**Comment by KyrosWeb** [comment]
Solved!
